# Generated by Django 6.0.2 on 2026-02-13 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('especialidad', models.CharField(choices=[('yoga', 'Yoga'), ('cross fit', 'Cross Fit'), ('aeróbic', 'Aeróbic'), ('hiit', 'HIIT'), ('pilates', 'Pilates')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('fecha_hora', models.DateTimeField()),
                ('cupo', models.IntegerField(default=20)),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], max_length=20)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='gym.instructormodel')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_alumno', models.CharField(max_length=20)),
                ('email_alumno', models.EmailField(max_length=254)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('codigo_reserva', models.CharField(max_length=10)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='gym.clasemodel')),
            ],
        ),
    ]
